version: '3.8'

services:
  fastapi_app:
    image: nayana1198/fastapi-app:latest
    container_name: fastapi_app
    ports:
      - "9000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
